fix CI/CD

diff --git a/.github/workflows/release-sdk.yml b/.github/workflows/release-sdk.yml
--- a/.github/workflows/release-sdk.yml
+++ b/.github/workflows/release-sdk.yml
@@ -6,22 +6,6 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
-
-      - name: Extract Version from Cargo.toml
-        id: extract_version
-        run: |
-          version=$(grep -m 1 '^version' Cargo.toml | awk -F\" '{print $2}')
-          echo "version=$version" >> $GITHUB_ENV
-
-      - name: Validate inputs
-        run: |
-            if [[ "${{ env.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-              echo "OK";
-            else
-              echo "Invalid tag format. Given: ${{ env.version }}";
-              exit 1;
-            fi
-
       - name: Checkout code
         uses: actions/checkout@v4
 
@@ -39,6 +23,21 @@ jobs:
 
       - name: Build the project
         run: cargo build --release
+
+      - name: Extract Version from Cargo.toml
+        id: extract_version
+        run: |
+          version=$(grep -m 1 '^version' Cargo.toml | awk -F\" '{print $2}')
+          echo "version=$version" >> $GITHUB_ENV
+
+      - name: Validate inputs
+        run: |
+            if [[ "${{ env.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+              echo "OK";
+            else
+              echo "Invalid tag format. Given: ${{ env.version }}";
+              exit 1;
+            fi
 
       - name: Create Git Tag
         env:
